### PR TITLE
add option to hide logging

### PR DESCRIPTION
**Pull request by benkaiser**
I use this module during testing and would like it if it had a way to disable all automatic output by the module.

### CODE REVIEW

**Comment by jcreigno** [comment]
That's nice, thanks for the contribution.

**Comment by benkaiser** [comment]
No worries.

Can this get published as version 2.2.4 by any chance?

**Comment by jcreigno** [comment]
Version 0.2.4 with your pull request published.

**Comment by benkaiser** [comment]
Thanks!

**Pull request merged**
